//! X11's side of the workspace policy, offline: an `X11Surface` over a dead
//! connection (no Xwayland). Every
//! property write fails, and the surface's own mirror is what compd's
//! `policy_host::x11` reads back to stay idempotent, so the mirror
//! semantics are the seam pinned here. The policy decision itself (D15,
//! `x11_suspended`) is pinned by policy's workspace tests.

use std::sync::atomic::AtomicBool;
use std::sync::{Arc, Weak};

use smithay::utils::Rectangle;
use smithay::xwayland::X11Surface;
use smithay::xwayland::xwm::Atoms;

/// An atom table with distinct values for the atoms these tests touch (the
/// rest stay 0, as smithay's own offline tests build it).
fn atoms() -> Atoms {
    // SAFETY: `Atoms` is generated by `x11rb::atom_manager!` and holds only
    // `u32` atom fields, for which the all-zero bit pattern is valid.
    let mut atoms: Atoms = unsafe { std::mem::zeroed() };
    atoms._NET_WM_STATE = 1;
    atoms._NET_WM_STATE_HIDDEN = 2;
    atoms._NET_WM_STATE_FULLSCREEN = 3;
    atoms._NET_WM_STATE_MAXIMIZED_HORZ = 4;
    atoms._NET_WM_STATE_MAXIMIZED_VERT = 5;
    atoms._NET_WM_DESKTOP = 6;
    atoms
}

fn window(xid: u32) -> X11Surface {
    X11Surface::new(
        None,
        xid,
        false,
        Weak::new(),
        atoms(),
        None,
        Rectangle::new((0, 0).into(), (100, 100).into()),
        Arc::new(AtomicBool::new(false)),
    )
}

/// `_NET_WM_DESKTOP`: the write fails with no server, and the mirror holds
/// the value anyway, so compd's compare-before-write skips a repeat.
#[test]
fn the_desktop_mirror_holds_what_was_written() {
    let window = window(7);
    assert_eq!(window.desktop(), None);
    assert!(window.set_desktop(2).is_err(), "no server: the write itself fails");
    assert_eq!(window.desktop(), Some(2));
}

/// `_NET_WM_STATE_HIDDEN` through `set_hidden_hint` (EWMH hint only, never
/// `WM_STATE = Iconic`): the mirror follows each change, and leaves the
/// other states alone.
#[test]
fn the_hidden_hint_mirror_follows_each_change() {
    let window = window(8);
    assert!(!window.is_hidden());
    let _ = window.set_hidden_hint(true);
    assert!(window.is_hidden());
    assert!(!window.is_fullscreen(), "only HIDDEN moved");
    let _ = window.set_hidden_hint(false);
    assert!(!window.is_hidden());
}

/// The four X11 requests reach the comp policy's queue. An X11 window's
/// `_NET_WM_DESKTOP` / `_NET_ACTIVE_WINDOW` / `WM_CHANGE_STATE` arrive as
/// `SurfaceEvent::Request`s against its X11 handle (the `XwmHandler` methods
/// queue them), the root `_NET_CURRENT_DESKTOP` as its own event. The
/// answers (refusals, the verbs they run) are policy-host's.
#[test]
fn x11_requests_queue_for_the_policy() {
    use dispatcher::wire::trait_::surface_event::{SurfaceEvent, SurfaceHandle, WindowRequest};
    use surfaces::SurfaceRole;

    let mut comp = world::comp::CompState::default();
    let handle = SurfaceHandle::X11(0x200001);
    comp.apply(SurfaceEvent::RoleTaken {
        handle: handle.clone(),
        role: SurfaceRole::X11 { override_redirect: false },
        parent: None,
    });
    for request in [WindowRequest::Desktop(1), WindowRequest::Activate, WindowRequest::Unminimize, WindowRequest::Raise] {
        comp.apply(SurfaceEvent::Request {
            handle: handle.clone(),
            request,
        });
    }
    comp.apply(SurfaceEvent::CurrentDesktop(2));
    let queued: Vec<WindowRequest> = comp.take_requests().into_iter().map(|(_, request)| request).collect();
    assert_eq!(
        queued,
        [WindowRequest::Desktop(1), WindowRequest::Activate, WindowRequest::Unminimize, WindowRequest::Raise]
    );
    assert_eq!(comp.take_desktop_requests(), [2]);
    assert!(comp.take_desktop_requests().is_empty(), "taken once");
}

/// The two-sided Motif pin.
/// compd decides X11 decoration from smithay's `X11Surface::is_decorated()`;
/// policy keeps its own reading of the hints. Driving the real
/// smithay path with the vendored offline hints setter and asserting the two
/// agree is what turns an inversion in a smithay bump into a red test.
#[test]
fn smithay_reads_motif_hints_as_policy_does() {
    use policy::x11::{DecorationMode, decoration_mode, motif_refuses_server_decorations};

    let window = window(9);
    assert!(!window.is_decorated(), "no hints: the client accepts WM decorations");
    // `_MOTIF_WM_HINTS` = [flags, functions, decorations, input_mode, status].
    for (flags, decorations) in [(1 << 1, 0), (1 << 1, 1), (0, 0), (1 << 0, 0), (1 << 1, u32::MAX)] {
        window.set_motif_hints_offline([flags, 0, decorations, 0, 0]);
        assert_eq!(
            window.is_decorated(),
            motif_refuses_server_decorations(flags, decorations),
            "flags {flags:#x}, decorations {decorations:#x}"
        );
    }
    window.set_motif_hints_offline([1 << 1, 0, 0, 0, 0]);
    assert_eq!(
        decoration_mode(false, true, false, window.is_decorated()),
        DecorationMode::ClientSide,
        "a refusal reaches the decision"
    );
}

/// An override-redirect menu's `WM_TRANSIENT_FOR`, read off the smithay
/// surface into `SurfaceEvent::TransientFor`, makes a move of its owner take
/// it along; the owner's registry record gains no `parent` (an X11 record
/// has none), and a cleared property lets go.
#[test]
fn an_owner_move_takes_its_override_redirect_menu() {
    use dispatcher::wire::trait_::surface_event::{SurfaceEvent, SurfaceHandle};
    use policy::workspaces::WorkspaceTarget;
    use surfaces::SurfaceRole;

    let mut comp = world::comp::CompState::default();
    let owner = window(0x400001);
    let menu = window(0x400002);
    menu.set_override_redirect_offline(true);
    menu.set_transient_for_offline(Some(0x400001));
    let mut ids = Vec::new();
    for (surface, override_redirect) in [(&owner, false), (&menu, true)] {
        comp.apply(SurfaceEvent::RoleTaken {
            handle: SurfaceHandle::x11(surface),
            role: SurfaceRole::X11 { override_redirect },
            parent: None,
        });
        comp.apply(SurfaceEvent::x11_transient_for(surface));
        let id = comp.registry.id_for_handle(&SurfaceHandle::x11(surface)).unwrap();
        comp.registry.set_mapped(id, true).unwrap();
        assert!(policy::workspaces::stamp_workspace_at_map(&mut comp.registry, id, false, 1));
        ids.push(id);
    }
    let (owner_id, menu_id) = (ids[0], ids[1]);
    assert_eq!(comp.registry.get(menu_id).unwrap().parent(), None, "no parent for an X11 record");
    assert_eq!(
        comp.registry.get(menu_id).unwrap().transient_for(),
        Some(&SurfaceHandle::X11(0x400001))
    );
    comp.workspaces
        .move_window(&mut comp.registry, None, owner_id, WorkspaceTarget::Index(2), None)
        .unwrap();
    assert_eq!(comp.registry.get(menu_id).unwrap().workspace(), Some(2), "the menu followed");
    // The client clears WM_TRANSIENT_FOR: the next move leaves the menu.
    menu.set_transient_for_offline(None);
    comp.apply(SurfaceEvent::x11_transient_for(&menu));
    comp.workspaces
        .move_window(&mut comp.registry, None, owner_id, WorkspaceTarget::Index(3), None)
        .unwrap();
    assert_eq!(comp.registry.get(menu_id).unwrap().workspace(), Some(2), "released");
}
