[package]
name = "render-gles"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[package.metadata.mixos]
component = "compd"
kind = "service"
layer = "desktop"
contract = "none"

[lints]
workspace = true

[features]
mode-synthesize = []
modifier-fallback = []

[dependencies]
model = { workspace = true }
slots = { workspace = true }
smithay = { workspace = true }
