[package]
name = "nested"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[package.metadata.mixos]
component = "compd"
kind = "service"
layer = "desktop"
contract = "none"

[lints]
workspace = true

[dependencies]
recorder = { workspace = true }
dispatcher = { workspace = true }
outputs = { workspace = true }
frames = { workspace = true }
graphics = { workspace = true }
ledger = { workspace = true }
model = { workspace = true }
render-gles = { workspace = true }
scenegraph = { workspace = true }
decor = { workspace = true }
screencopy = { workspace = true }
seat = { workspace = true }
slots = { workspace = true }
protocols = { workspace = true }
world = { workspace = true }
smithay = { workspace = true }
