// SPDX-License-Identifier: MIT OR Apache-2.0
//! Syntax highlighting for the MixOS editor (ced): msedit's `lsh` — a small
//! compiler from `definitions/*.lsh` to bytecode plus a line-oriented runtime
//! — vendored from microsoft/edit@826b4c0 (MIT; `vendor/README.md`), with a
//! chunk-source adapter so any text store can be highlighted.
//!
//! Contracts (ced E1 plan `_plan/2026-09-26-ced-e1-implementation.md` §1.2,
//! frozen in Stage S; bodies land in Stage E1b):
//! - [`defs`] is **pre-generated and committed** (`examples/gen.rs` writes it,
//!   `tests/defs_fresh.rs` proves it is current). No build script.
//! - [`highlighter::Highlighter`] reads a [`LineSource`] line by line; lines
//!   longer than [`highlighter::MAX_LINE_LEN`] (32 KiB) are left unhighlighted
//!   (upstream behaviour).
//! - [`cache::Cache`] keeps a runtime checkpoint every [`cache::INTERVAL`]
//!   (1024, pinned in every profile — upstream used 16 under
//!   `debug_assertions`) so random seeks cost at most one interval.
//! - **Line numbers are 1-based** everywhere in this API, like
//!   `mixos-edit-core` and the `edit` wire.
//! - No mutable statics anywhere in this crate or its vendored dependencies.

pub mod cache;
pub mod defs;
pub mod highlighter;

/// The vendored runtime types (`Language`, `Highlight`).
pub use lsh::runtime;
use lsh::runtime::Language;

/// The language whose `#[path]` globs match `path` first (upstream's
/// `process_file_associations`, in `FILE_ASSOCIATIONS` priority order).
pub fn language_for_path(path: &std::path::Path) -> Option<&'static Language> {
    let path = path.as_os_str().as_encoded_bytes();
    defs::FILE_ASSOCIATIONS
        .iter()
        .find(|(glob, _)| stdext::glob::glob_match(glob.as_bytes(), path))
        .map(|&(_, language)| language)
}

/// The language with this lsh `id` (`"rust"`, `"git-commit"`, …).
pub fn language_by_id(id: &str) -> Option<&'static Language> {
    defs::LANGUAGES.iter().find(|l| l.id == id)
}

/// The language with this display name (`"Rust"`, `"Markdown"`, …), compared
/// ASCII-case-insensitively.
pub fn language_by_name(name: &str) -> Option<&'static Language> {
    defs::LANGUAGES
        .iter()
        .find(|l| l.name.eq_ignore_ascii_case(name))
}

/// Regenerates `src/defs.rs` from the vendored definitions. Used by
/// `examples/gen.rs` and `tests/defs_fresh.rs` only: the lsh compiler panics on
/// patterns it does not support, so it never runs inside an editor.
#[doc(hidden)]
pub mod compiler {
    use std::path::Path;

    use stdext::arena::scratch_arena;

    /// Committed location of the generated file, relative to this crate.
    pub const DEFS_PATH: &str = "src/defs.rs";

    const HEADER: &str = "\
//! Compiled lsh definitions: bytecode, strings, charsets, the language table
//! and file associations.
//!
//! @generated by `cargo run --release -p syntax --example gen` from
//! `../../../../vendor/msedit/lsh/definitions/*.lsh` (the generator msedit runs from its build
//! script, `crates/edit/build/main.rs`); `tests/defs_fresh.rs` proves it is
//! current. Do not edit. Two changes to the upstream output: the compiler's
//! Mermaid dump of its IR is left out (it prints node addresses, so it differs
//! on every run), and `HighlightKind` also derives `Hash`.

";

    /// The vendored definitions directory.
    pub fn definitions_dir() -> &'static Path {
        lsh::compiler::builtin_definitions_path()
    }

    /// The full text of `src/defs.rs`, deterministic for a given definitions
    /// directory.
    pub fn generate_defs() -> Result<String, String> {
        let scratch = scratch_arena(None);
        let mut generator = lsh::compiler::Generator::new(&scratch);
        generator
            .read_directory(definitions_dir())
            .map_err(|e| e.to_string())?;
        let raw = generator.generate_rust().map_err(|e| e.to_string())?;
        shape(&raw)
    }

    fn shape(raw: &str) -> Result<String, String> {
        const DERIVE: &str = "#[derive(Debug, Clone, Copy, PartialEq, Eq)]\npub enum HighlightKind";
        const LANGUAGES: &str = "\n#[rustfmt::skip] pub static LANGUAGES";
        let mermaid = raw
            .find("/*\nflowchart")
            .ok_or("generator output: no IR dump found")?;
        let languages = raw
            .find(LANGUAGES)
            .ok_or("generator output: no LANGUAGES table")?;
        if languages < mermaid || !raw.contains(DERIVE) {
            return Err("generator output: unexpected layout".to_string());
        }
        let body = format!("{}{}", &raw[..mermaid], &raw[languages..]);
        let body = body.replacen(
            DERIVE,
            "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\npub enum HighlightKind",
            1,
        );
        Ok(format!("{HEADER}{body}"))
    }
}

/// A text store the highlighter can read from: returns the contiguous bytes
/// starting at `offset` up to some chunk boundary (empty at/after the end).
/// A line may span several chunks; the highlighter assembles it. Unlike
/// `mixos-edit-core`'s measurement adapter, chunks may split grapheme
/// clusters — lsh works on bytes.
pub trait LineSource {
    fn read_forward(&self, offset: usize) -> &[u8];

    /// Indexed end of 1-based `line`, including its newline when present.
    /// Sources without a line index may leave this unknown. The highlighter
    /// uses it only to skip lines that exceed its highlighting limit.
    fn indexed_line_end(&self, _line: usize) -> Option<usize> {
        None
    }
}

impl LineSource for &[u8] {
    fn read_forward(&self, offset: usize) -> &[u8] {
        self.get(offset..).unwrap_or(&[])
    }
}

impl LineSource for str {
    fn read_forward(&self, offset: usize) -> &[u8] {
        self.as_bytes().get(offset..).unwrap_or(&[])
    }
}
