[package]
name = "scenegraph"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[package.metadata.mixos]
component = "compd"
kind = "service"
layer = "desktop"
contract = "none"

[lints]
workspace = true

[dependencies]
dispatcher = { workspace = true }
effects = { workspace = true }
ui = { workspace = true }
model = { workspace = true }
render-gles = { workspace = true }
seat = { workspace = true }
slots = { workspace = true }
world = { workspace = true }
smithay = { workspace = true }
