// Developer logging: bring error!/warn!/info!/trace!/abort! into scope.
//
// compd (Q-K / D11): everything that links libav — the bindgen bindings, the C
// accessor shim, the VA-API and NVENC encoders and their CUDA/EGL plumbing — is
// behind the opt-in `capture-ffmpeg` feature. Without it this module keeps its
// public API (settings accessors, `CaptureEncoder`, the encoder types) but the
// encoders come from `stub` and refuse to start, so the default compd binary has
// no ffmpeg link.

/// Raw libav (ffmpeg 8.x) bindings, generated by `build.rs` via bindgen.
#[cfg(feature = "capture-ffmpeg")]
#[allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    improper_ctypes
)]
pub mod ffi;

mod capture;
#[cfg(feature = "capture-ffmpeg")]
mod common;
#[cfg(feature = "capture-ffmpeg")]
pub mod cuda;
#[cfg(feature = "capture-ffmpeg")]
#[macro_use]
mod dynload;
#[cfg(feature = "capture-ffmpeg")]
pub mod egl;
#[cfg(feature = "capture-ffmpeg")]
pub mod nvenc;
#[cfg(feature = "capture-ffmpeg")]
pub mod nvenc_cuda;
#[cfg(not(feature = "capture-ffmpeg"))]
mod stub;
#[cfg(feature = "capture-ffmpeg")]
pub mod thread;
#[cfg(feature = "capture-ffmpeg")]
pub mod vaapi;

pub use capture::*;
#[cfg(feature = "capture-ffmpeg")]
pub use nvenc::NvencEncoder;
#[cfg(feature = "capture-ffmpeg")]
pub use nvenc_cuda::{Codec, NvencCudaEncoder};
#[cfg(not(feature = "capture-ffmpeg"))]
pub use stub::{Codec, EncoderThread, NOT_BUILT, NvencCudaEncoder, NvencEncoder, VaapiEncoder};
#[cfg(feature = "capture-ffmpeg")]
pub use thread::EncoderThread;
#[cfg(feature = "capture-ffmpeg")]
pub use vaapi::VaapiEncoder;

/// Whether this build links libav and can encode video (`capture-ffmpeg`).
pub const FFMPEG_BUILT: bool = cfg!(feature = "capture-ffmpeg");
